<a href="https://colab.research.google.com/github/samyam200200/python/blob/master/ArtificialNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
#import
dataset=pd.read_csv("Churn_Modelling.csv")
X=dataset.iloc[:,3:13].values
Y=dataset.iloc[:,13].values

In [10]:
#one hot encoding variables
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
# Country column
ct = ColumnTransformer([("Geo", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

# Male/Female
labelencoder_X = LabelEncoder()
X[:, 4] = labelencoder_X.fit_transform(X[:, 4])
X = X.astype('float64')

In [11]:
#removing 1 dummy varibale ie 0 
X=X[:,1:]

In [12]:
#Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.20, random_state=0)

In [13]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
#Making ANN
# Importing Keras
import keras

Using TensorFlow backend.


In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
#Initalizing ANN
classifier=Sequential()

In [17]:
# Adding first layer -  input layera and first hidden layer
# units = output_dim (i.e. number of hidden layers equal to inputlayers(11)+outputlayers(1)/2)
# init=kernel_initializer (initial weights)
# input_dim (input layers)
classifier.add(Dense(units=6, kernel_initializer="uniform", activation="relu", input_dim=11))

In [18]:
#adding new layer
#this is added to previous neural network, its not needed to add input layer
classifier.add(Dense(units=6, kernel_initializer="uniform", activation="relu"))

In [19]:
#output layer
#softmax for more than one output
classifier.add(Dense(units=1, kernel_initializer="uniform", activation="sigmoid"))

In [20]:
#Compiling ANN
#adam is for stochastic gradient descent
#loss function is for the weights, here for logistic regression we will use lograthmic loss
#more than 2 varibale categorical_crossentropy
#what is used to improve the goodness of model
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])

In [21]:
# fitting ANN into the dataset
#also pass batch size
# and pass epoch (repeating previous spteps this many times)
classifier.fit(X_train, Y_train, batch_size=10, nb_epoch=100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  after removing the cwd from sys.path.


Epoch 1/100
8000/8000 [==============================] - 4s 506us/step - loss: 0.4838 - accuracy: 0.7955
Epoch 2/100
8000/8000 [==============================] - 2s 292us/step - loss: 0.4278 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 288us/step - loss: 0.4226 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 287us/step - loss: 0.4187 - accuracy: 0.8176
Epoch 5/100
8000/8000 [==============================] - 2s 273us/step - loss: 0.4166 - accuracy: 0.8249
Epoch 6/100
8000/8000 [==============================] - 2s 269us/step - loss: 0.4149 - accuracy: 0.8285
Epoch 7/100
8000/8000 [==============================] - 2s 269us/step - loss: 0.4136 - accuracy: 0.8299
Epoch 8/100
8000/8000 [==============================] - 2s 270us/step - loss: 0.4121 - accuracy: 0.8322
Epoch 9/100
8000/8000 [==============================] - 2s 270us/step - loss: 0.4112 - accuracy: 0.8309
Epoch 10/100
8000/8000 [==============================]

In [22]:
# predicting in test set
Y_pred=classifier.predict(X_test)
Y_pred

array([[0.23839454],
       [0.3323294 ],
       [0.10585386],
       ...,
       [0.18298544],
       [0.13100782],
       [0.1398023 ]], dtype=float32)

In [23]:
#All greater than 0.5 is true less than 0.5 is false
Y_pred=(Y_pred>0.5)

In [24]:
#  creating confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test, Y_pred)
cm

array([[1544,   51],
       [ 266,  139]])

In [25]:
# new prediction
#in horizontal matrix (using double [[]]) - creating 2d array
new_prediction=classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction=(new_prediction>0.5)
new_prediction

array([[False]])